FROM gradle:7.6-jdk17 AS builder
WORKDIR /app

COPY . .

RUN gradle clean build -x test

#
FROM eclipse-temurin:17-jdk-jammy
ENV TZ=Asia/Seoul
WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8083
ENTRYPOINT ["java", "-jar", "app.jar"]
